# .github/workflows/dev-to-main.yml
name: Validate Dev Branch before Main Merge

on:
  pull_request:
    branches:
      - main # This workflow runs only on PRs targeting the 'main' branch
    types: [opened, synchronize] # Runs when PR is opened or new commits are pushed to it

jobs:
  integration-test:
    name: Run Integration Tests on Dev Branch
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout the code from the PR
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 — Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3 — Create .env file for backend tests 🔑
      # This ensures tests run with the necessary environment variables
      - name: Create .env file for backend
        run: |
          echo "Creating .env file in /server..."
          cd server
          echo "MONGO_URI=${{ secrets.MONGO_URI_TEST }}" >> .env # Use a test DB if you have one
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "✅ .env file created for testing."
      
      # Step 4 — Install and Test Backend
      - name: Install and Test Backend
        run: |
          echo "Running backend integration tests..."
          cd server
          npm install
          npm test --if-present
          echo "✅ Backend tests passed."

      # Step 5 — Install, Build, and Test Frontend
      - name: Install, Build, and Test Frontend
        run: |
          echo "Running frontend integration tests..."
          cd frontend
          npm install
          npm run build
          # npm test --if-present # Uncomment if you have frontend tests
          echo "✅ Frontend validation passed."